export type ShippingMethod = {
  id: string;
  name: string;
  service: string;
  type: "mercari" | "other";
  price: number;
  maxLength?: number;
  maxWidth?: number;
  maxHeight?: number;
  maxTotalCm?: number;
  maxWeightGram?: number;
  notes?: string;
};

export const shippingServices: { name: string; type: "mercari" | "other" }[] = [
  { name: "らくらくメルカリ便", type: "mercari" },
  { name: "ゆうゆうメルカリ便", type: "mercari" },
  { name: "エコメルカリ便", type: "mercari" },
  { name: "たのメル便", type: "mercari" },
  { name: "レターパック", type: "other" },
  { name: "定形郵便", type: "other" },
  { name: "定形外郵便 規格内", type: "other" },
  { name: "定形外郵便 規格外", type: "other" },
  { name: "ゆうメール", type: "other" },
  { name: "クリックポスト", type: "other" },
  { name: "スマートレター", type: "other" },
  { name: "ヤマト運輸", type: "other" },
];

export const shippingMethods: ShippingMethod[] = [
  {
    id: "rakuraku-nekopos",
    name: "ネコポス",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 210,
    maxTotalCm: 60,
    maxLength: 34,
    maxHeight: 3,
    maxWeightGram: 1000,
    notes: "3辺合計60cm以内・長辺34cm以内・厚さ3cm以内・重さ1kg以内",
  },
  {
    id: "rakuraku-compact",
    name: "宅急便コンパクト",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 450,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 5,
    notes: "専用BOXが必要・箱代別途",
  },
  {
    id: "rakuraku-60",
    name: "宅急便 60サイズ",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 750,
    maxTotalCm: 60,
    maxWeightGram: 2000,
  },
  {
    id: "rakuraku-80",
    name: "宅急便 80サイズ",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 850,
    maxTotalCm: 80,
    maxWeightGram: 5000,
  },
  {
    id: "rakuraku-100",
    name: "宅急便 100サイズ",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 1050,
    maxTotalCm: 100,
    maxWeightGram: 10000,
  },
  {
    id: "rakuraku-120",
    name: "宅急便 120サイズ",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 1200,
    maxTotalCm: 120,
    maxWeightGram: 15000,
  },
  {
    id: "rakuraku-140",
    name: "宅急便 140サイズ",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 1450,
    maxTotalCm: 140,
    maxWeightGram: 20000,
  },
  {
    id: "rakuraku-160",
    name: "宅急便 160サイズ",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 1700,
    maxTotalCm: 160,
    maxWeightGram: 25000,
  },
  {
    id: "rakuraku-170",
    name: "宅急便 170サイズ",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 2100,
    maxTotalCm: 170,
    maxWeightGram: 30000,
    notes: "ヤマト運輸営業所または集荷のみ対応",
  },
  {
    id: "rakuraku-180",
    name: "宅急便 180サイズ",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 2400,
    maxTotalCm: 180,
    maxWeightGram: 30000,
    notes: "ヤマト運輸営業所または集荷のみ対応",
  },
  {
    id: "rakuraku-200",
    name: "宅急便 200サイズ",
    service: "らくらくメルカリ便",
    type: "mercari",
    price: 2500,
    maxTotalCm: 200,
    maxWeightGram: 30000,
    notes: "ヤマト運輸営業所または集荷のみ対応",
  },

  {
    id: "yuyu-mini",
    name: "ゆうパケットポストmini",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 160,
    maxLength: 21.1,
    maxWidth: 16.8,
    maxHeight: 3,
    maxWeightGram: 2000,
    notes: "専用封筒が必要",
  },
  {
    id: "yuyu-post",
    name: "ゆうパケットポスト",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 215,
    maxTotalCm: 60,
    maxLength: 34,
    maxHeight: 3,
    maxWeightGram: 2000,
    notes: "専用シールまたは専用箱が必要",
  },
  {
    id: "yuyu-packet",
    name: "ゆうパケット",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 230,
    maxLength: 34,
    maxWidth: 23,
    maxHeight: 3,
    maxWeightGram: 1000,
    notes: "長辺34cm以内・厚さ3cm以内・重さ1kg以内",
  },
  {
    id: "yuyu-plus",
    name: "ゆうパケットプラス",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 455,
    maxLength: 24,
    maxWidth: 17,
    maxHeight: 7,
    maxWeightGram: 2000,
    notes: "専用BOXが必要",
  },
  {
    id: "yupack-60",
    name: "ゆうパック 60サイズ",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 750,
    maxTotalCm: 60,
    maxWeightGram: 25000,
  },
  {
    id: "yupack-80",
    name: "ゆうパック 80サイズ",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 870,
    maxTotalCm: 80,
    maxWeightGram: 25000,
  },
  {
    id: "yupack-100",
    name: "ゆうパック 100サイズ",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 1070,
    maxTotalCm: 100,
    maxWeightGram: 25000,
  },
  {
    id: "yupack-120",
    name: "ゆうパック 120サイズ",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 1200,
    maxTotalCm: 120,
    maxWeightGram: 25000,
  },
  {
    id: "yupack-140",
    name: "ゆうパック 140サイズ",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 1450,
    maxTotalCm: 140,
    maxWeightGram: 25000,
  },
  {
    id: "yupack-160",
    name: "ゆうパック 160サイズ",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 1700,
    maxTotalCm: 160,
    maxWeightGram: 25000,
  },
  {
    id: "yupack-170",
    name: "ゆうパック 170サイズ",
    service: "ゆうゆうメルカリ便",
    type: "mercari",
    price: 1900,
    maxTotalCm: 170,
    maxWeightGram: 25000,
  },

  {
    id: "eco-delivery-60",
    name: "エコ宅配便 60サイズ",
    service: "エコメルカリ便",
    type: "mercari",
    price: 730,
    maxTotalCm: 60,
    maxWeightGram: 10000,
    notes: "対応エリアのみ",
  },
  {
    id: "eco-delivery-80",
    name: "エコ宅配便 80サイズ",
    service: "エコメルカリ便",
    type: "mercari",
    price: 730,
    maxTotalCm: 80,
    maxWeightGram: 10000,
    notes: "対応エリアのみ",
  },
  {
    id: "eco-delivery-100",
    name: "エコ宅配便 100サイズ",
    service: "エコメルカリ便",
    type: "mercari",
    price: 730,
    maxTotalCm: 100,
    maxWeightGram: 10000,
    notes: "対応エリアのみ",
  },
  {
    id: "eco-door-60",
    name: "エコ置き配発送 60サイズ",
    service: "エコメルカリ便",
    type: "mercari",
    price: 730,
    maxTotalCm: 60,
    maxWeightGram: 20000,
    notes: "対応エリアのみ",
  },
  {
    id: "eco-door-80",
    name: "エコ置き配発送 80サイズ",
    service: "エコメルカリ便",
    type: "mercari",
    price: 730,
    maxTotalCm: 80,
    maxWeightGram: 20000,
    notes: "対応エリアのみ",
  },
  {
    id: "eco-door-100",
    name: "エコ置き配発送 100サイズ",
    service: "エコメルカリ便",
    type: "mercari",
    price: 730,
    maxTotalCm: 100,
    maxWeightGram: 20000,
    notes: "対応エリアのみ",
  },
  {
    id: "eco-door-120",
    name: "エコ置き配発送 120サイズ",
    service: "エコメルカリ便",
    type: "mercari",
    price: 730,
    maxTotalCm: 120,
    maxWeightGram: 20000,
    notes: "対応エリアのみ",
  },
  {
    id: "eco-door-140",
    name: "エコ置き配発送 140サイズ",
    service: "エコメルカリ便",
    type: "mercari",
    price: 730,
    maxTotalCm: 140,
    maxWeightGram: 20000,
    notes: "対応エリアのみ",
  },
  {
    id: "eco-door-160",
    name: "エコ置き配発送 160サイズ",
    service: "エコメルカリ便",
    type: "mercari",
    price: 730,
    maxTotalCm: 160,
    maxWeightGram: 20000,
    notes: "対応エリアのみ",
  },

  {
    id: "tano-80",
    name: "たのメル便 80サイズ",
    service: "たのメル便",
    type: "mercari",
    price: 1700,
    maxTotalCm: 80,
    maxWeightGram: 50000,
    notes: "家具・大型商品向け",
  },
  {
    id: "tano-120",
    name: "たのメル便 120サイズ",
    service: "たのメル便",
    type: "mercari",
    price: 2400,
    maxTotalCm: 120,
    maxWeightGram: 50000,
    notes: "家具・大型商品向け",
  },
  {
    id: "tano-160",
    name: "たのメル便 160サイズ",
    service: "たのメル便",
    type: "mercari",
    price: 3400,
    maxTotalCm: 160,
    maxWeightGram: 50000,
    notes: "家具・大型商品向け",
  },
  {
    id: "tano-200",
    name: "たのメル便 200サイズ",
    service: "たのメル便",
    type: "mercari",
    price: 5000,
    maxTotalCm: 200,
    maxWeightGram: 50000,
    notes: "家具・大型商品向け",
  },
  {
    id: "tano-250",
    name: "たのメル便 250サイズ",
    service: "たのメル便",
    type: "mercari",
    price: 8600,
    maxTotalCm: 250,
    maxWeightGram: 150000,
    notes: "家具・大型商品向け",
  },
  {
    id: "tano-300",
    name: "たのメル便 300サイズ",
    service: "たのメル便",
    type: "mercari",
    price: 12000,
    maxTotalCm: 300,
    maxWeightGram: 150000,
    notes: "家具・大型商品向け",
  },
  {
    id: "tano-350",
    name: "たのメル便 350サイズ",
    service: "たのメル便",
    type: "mercari",
    price: 18500,
    maxTotalCm: 350,
    maxWeightGram: 150000,
    notes: "家具・大型商品向け",
  },
  {
    id: "tano-400",
    name: "たのメル便 400サイズ",
    service: "たのメル便",
    type: "mercari",
    price: 25400,
    maxTotalCm: 400,
    maxWeightGram: 150000,
    notes: "家具・大型商品向け",
  },
  {
    id: "tano-450",
    name: "たのメル便 450サイズ",
    service: "たのメル便",
    type: "mercari",
    price: 33000,
    maxTotalCm: 450,
    maxWeightGram: 150000,
    notes: "家具・大型商品向け",
  },

  {
    id: "letterpack-light",
    name: "レターパックライト",
    service: "レターパック",
    type: "other",
    price: 430,
    maxLength: 34,
    maxWidth: 24.8,
    maxHeight: 3,
    maxWeightGram: 4000,
    notes: "追跡あり",
  },
  {
    id: "letterpack-plus",
    name: "レターパックプラス",
    service: "レターパック",
    type: "other",
    price: 600,
    maxLength: 34,
    maxWidth: 24.8,
    maxWeightGram: 4000,
    notes: "対面受け取り・厚さ制限なし",
  },
  {
    id: "teikei-50g",
    name: "定形郵便 ～50g",
    service: "定形郵便",
    type: "other",
    price: 110,
    maxLength: 23.5,
    maxWidth: 12,
    maxHeight: 1,
    maxWeightGram: 50,
  },
  {
    id: "teikei-100g",
    name: "定形郵便 ～100g",
    service: "定形郵便",
    type: "other",
    price: 180,
    maxLength: 23.5,
    maxWidth: 12,
    maxHeight: 1,
    maxWeightGram: 100,
  },
  {
    id: "teikeigai-nai-50",
    name: "定形外郵便(規格内) ～50g",
    service: "定形外郵便 規格内",
    type: "other",
    price: 140,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 50,
  },
  {
    id: "teikeigai-nai-100",
    name: "定形外郵便(規格内) ～100g",
    service: "定形外郵便 規格内",
    type: "other",
    price: 180,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 100,
  },
  {
    id: "teikeigai-nai-150",
    name: "定形外郵便(規格内) ～150g",
    service: "定形外郵便 規格内",
    type: "other",
    price: 270,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 150,
  },
  {
    id: "teikeigai-nai-250",
    name: "定形外郵便(規格内) ～250g",
    service: "定形外郵便 規格内",
    type: "other",
    price: 320,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 250,
  },
  {
    id: "teikeigai-nai-500",
    name: "定形外郵便(規格内) ～500g",
    service: "定形外郵便 規格内",
    type: "other",
    price: 510,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 500,
  },
  {
    id: "teikeigai-nai-1000",
    name: "定形外郵便(規格内) ～1kg",
    service: "定形外郵便 規格内",
    type: "other",
    price: 750,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 1000,
  },
  {
    id: "teikeigai-gai-50",
    name: "定形外郵便(規格外) ～50g",
    service: "定形外郵便 規格外",
    type: "other",
    price: 260,
    maxTotalCm: 90,
    maxLength: 60,
    maxWeightGram: 50,
  },
  {
    id: "teikeigai-gai-100",
    name: "定形外郵便(規格外) ～100g",
    service: "定形外郵便 規格外",
    type: "other",
    price: 290,
    maxTotalCm: 90,
    maxLength: 60,
    maxWeightGram: 100,
  },
  {
    id: "teikeigai-gai-150",
    name: "定形外郵便(規格外) ～150g",
    service: "定形外郵便 規格外",
    type: "other",
    price: 390,
    maxTotalCm: 90,
    maxLength: 60,
    maxWeightGram: 150,
  },
  {
    id: "teikeigai-gai-250",
    name: "定形外郵便(規格外) ～250g",
    service: "定形外郵便 規格外",
    type: "other",
    price: 450,
    maxTotalCm: 90,
    maxLength: 60,
    maxWeightGram: 250,
  },
  {
    id: "teikeigai-gai-500",
    name: "定形外郵便(規格外) ～500g",
    service: "定形外郵便 規格外",
    type: "other",
    price: 660,
    maxTotalCm: 90,
    maxLength: 60,
    maxWeightGram: 500,
  },
  {
    id: "teikeigai-gai-1000",
    name: "定形外郵便(規格外) ～1kg",
    service: "定形外郵便 規格外",
    type: "other",
    price: 920,
    maxTotalCm: 90,
    maxLength: 60,
    maxWeightGram: 1000,
  },
  {
    id: "teikeigai-gai-2000",
    name: "定形外郵便(規格外) ～2kg",
    service: "定形外郵便 規格外",
    type: "other",
    price: 1350,
    maxTotalCm: 90,
    maxLength: 60,
    maxWeightGram: 2000,
  },
  {
    id: "teikeigai-gai-4000",
    name: "定形外郵便(規格外) ～4kg",
    service: "定形外郵便 規格外",
    type: "other",
    price: 1750,
    maxTotalCm: 90,
    maxLength: 60,
    maxWeightGram: 4000,
  },
  {
    id: "you-mail-150",
    name: "ゆうメール ～150g",
    service: "ゆうメール",
    type: "other",
    price: 190,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 150,
  },
  {
    id: "you-mail-250",
    name: "ゆうメール ～250g",
    service: "ゆうメール",
    type: "other",
    price: 230,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 250,
  },
  {
    id: "you-mail-500",
    name: "ゆうメール ～500g",
    service: "ゆうメール",
    type: "other",
    price: 320,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 500,
  },
  {
    id: "you-mail-1000",
    name: "ゆうメール ～1kg",
    service: "ゆうメール",
    type: "other",
    price: 380,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 1000,
  },
  {
    id: "click-post",
    name: "クリックポスト",
    service: "クリックポスト",
    type: "other",
    price: 185,
    maxLength: 34,
    maxWidth: 25,
    maxHeight: 3,
    maxWeightGram: 1000,
  },
  {
    id: "smart-letter",
    name: "スマートレター",
    service: "スマートレター",
    type: "other",
    price: 210,
    maxLength: 25,
    maxWidth: 17,
    maxHeight: 2,
    maxWeightGram: 1000,
  },
  {
    id: "koneko-420",
    name: "こねこ便420",
    service: "ヤマト運輸",
    type: "other",
    price: 420,
    maxLength: 34,
    maxWidth: 24.8,
    maxHeight: 3,
    maxWeightGram: 2000,
    notes: "一部地域のみ対応",
  },
];
